name: sync up to codecommit

on:
  push:
    branches:
      - main

env:

  AWS_REGION : "ca-central-1"

permissions:
      id-token: write 
      contents: read
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Debug ownership and Git configuration
        run: |
          ls -l .
          ls -l /
          pwd
          ls -l /.github
          ls -l /github/workspace
          git config --global --list
          git config --list
      - name: Change ownership of the repository directory
        run: sudo chown -R $USER:$USER /github/workspace
      - name: Debug ownership and Git configuration
        run: |
          ls -l /github
          ls -l /github/workspace
          git config --global --list
          git config --list
      - name: Configure Git to recognize safe directory
        run: git config --global --add safe.directory /github/workspace
      - name: Debug ownership and Git configuration
        run: |
          ls -l /github
          ls -l /github/workspace
          git config --global --list
          git config --list
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::772335252546:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1
        with:
          repository_name: personal-s3-webpage
          aws_region: ca-central-1
